name: myschoolapp ci Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image with tag
      run: docker build . --file Dockerfile --tag myschoolapp-site:${{github.run_number}}
    - name: Build latest 
      run: docker build . --file Dockerfile --tag myschoolapp-site
    - name: Login to Docker hub
      run: docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
    - name: Tag image 
      run: docker tag myschoolapp-site:${{github.run_number}} ${{secrets.USERNAME}}/myschoolapp-site:${{github.run_number}}
    - name: Push Image 
      run: docker push  ${{secrets.USERNAME}}/myschoolapp-site:${{github.run_number}}
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
       - name: SSH to server
         uses: appleboy/ssh-action@v1.0.3
         with:
          host: ${{secrets.HOST}}
          username: ${{vars.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            docker stop myschoolapp || echo ""
            docker rm myschoolapp || echo ""
            docker run -d --name myschoolapp -p 8086:80 ${{secrets.USERNAME}}/myschoolapp-site:${{github.run_number}}